### ISSUE TITLE
Custom Variables

### ISSUE THREAD

**Issue by Zeryther** [codebucketdev/BungeeSigns#1]
How do I use custom variables?

**Comment by codebucketdev** [comment]
Hello, 
to add custom variables, you must add them as rule in your layout.yml :)

Example:

```
variables:
    motdfix: # name of the variable -> %motdfix%
        type: REPLACE # type of rule -> SPLIT, SUBSTRING or REPLACE
        arguments: 'Death,Deathmatch' # Arguments for the rule. In this example, I set as Argument to replace Death in the Motd to Deathmatch.

```

And to use the Example above, you must only use %motdfix% as placeholder in your layout.
This would show the Motd "§5Deathmatch" instead of "§5Death" :)

P.S: Sorry for the late response ^^
